### ISSUE TITLE
Dumpling fails with AttributeError: DumplingConfig instance has no attribute 'dbgpath'

### ISSUE THREAD

**Issue by mellinoe** [Microsoft/dumpling#30]
Moved over from https://github.com/dotnet/corefx/issues/21225. It seems like dumpling is successfully uploading the crash dump, but is also trying to do extra triage steps with tools that aren't available. Dumpling should just detect that those tools aren't available and skip that step.

**Comment by danmosemsft** [comment]
@DrewScoggins would you mind fixing this? it's pretty ugly. I'm all about trying to make it easy and actionable, and a callstack in the middle doesn't help.

```
2017-09-14 19:28:33,981: INFO: proc(54): run_and_log_output: Output: processing dump file /home/helixbot/dotnetbuild/work/63c960d2-345d-4e4b-9f41-7a0d1562a6de/Work/633e7455-2d0e-4c86-8181-401c7fac1dbe/Unzip/core
2017-09-14 19:28:33,982: INFO: proc(54): run_and_log_output: Output: creating dumpling dump b35f41c3ed0a9f7f028a019a76892b1d96f52f37
2017-09-14 19:28:33,982: INFO: proc(54): run_and_log_output: Output: uploading artifact b35f41c3ed0a9f7f028a019a76892b1d96f52f37 core
2017-09-14 19:28:33,982: INFO: proc(54): run_and_log_output: Output: Traceback (most recent call last):
2017-09-14 19:28:33,982: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 1128, in <module>
2017-09-14 19:28:33,982: INFO: proc(54): run_and_log_output: Output:     main(sys.argv)
2017-09-14 19:28:33,982: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 1123, in main
2017-09-14 19:28:33,982: INFO: proc(54): run_and_log_output: Output:     cmdProc.Process(config)
2017-09-14 19:28:33,982: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 529, in Process
2017-09-14 19:28:33,982: INFO: proc(54): run_and_log_output: Output:     self.Upload(config)
2017-09-14 19:28:33,983: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 624, in Upload
2017-09-14 19:28:33,983: INFO: proc(54): run_and_log_output: Output:     self.UploadDump(config)
2017-09-14 19:28:33,983: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 644, in UploadDump
2017-09-14 19:28:33,983: INFO: proc(54): run_and_log_output: Output:     self._triage_dump(dumpid, config.dumppath, config)
2017-09-14 19:28:33,983: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 812, in _triage_dump
2017-09-14 19:28:33,983: INFO: proc(54): run_and_log_output: Output:     if config.dbgpath is None:
2017-09-14 19:28:33,983: INFO: proc(54): run_and_log_output: Output: AttributeError: DumplingConfig instance has no attribute 'dbgpath'
2017-09-14 19:28:33,995: INFO: proc(54): run_and_log_output: Output: Trying to find crash dumps for project: System.Net.Security.Tests
2017-09-14 19:28:33,995: INFO: proc(54): run_and_log_output: Output: Uploading dump file: /home/helixbot/dotnetbuild/work/63c960d2-345d-4e4b-9f41-7a0d1562a6de/Work/633e7455-2d0e-4c86-8181-401c7fac1dbe/Unzip/core
2017-09-14 19:28:33,996: INFO: proc(54): run_and_log_output: Output: ~/dotnetbuild/work/63c960d2-345d-4e4b-9f41-7a0d1562a6de/Work/633e7455-2d0e-4c86-8181-401c7fac1dbe/Unzip
2017-09-14 19:28:33,997: INFO: proc(54): run_and_log_output: Output: Finished running tests. End time=19:28:33. Return value was 134
2017-09-14 19:28:33,998: INFO: proc(54): run_and_log_output: Output: Unable to find executable corerun
2017-09-14 19:28:34,000: INFO: proc(54): run_and_log_output: Output: Copying core file core to /tmp/coredumps
2017-09-14 19:28:34,108: INFO: proc(58): run_and_log_output: Exit Code: 134
```

**Comment by DrewScoggins** [comment]
Yes, I can take a look at this.

**Comment by danmosemsft** [comment]
Haven't seen for a while.
